### ISSUE TITLE
SNOW-861919: Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: No module named 'snowflake.connector.arrow_iterator'

### ISSUE THREAD

**Issue by sfc-gh-anugupta** [Snowflake-Labs/snowcli#234] opened 2023-07-12 06:45 UTC
### What happened

Anyone else use brew to install snowcli and get this error when running snowcli?
Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: No module named 'snowflake.connector.arrow_iterator'

Most of the commands work, but I did notice things like lookup are impacted by this error:
snow snowpark package lookup pandas
Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: No module named 'snowflake.connector.arrow_iterator'

**Comment by sfc-gh-anugupta** [comment] 2023-07-12 06:46
@sfc-gh-turbaszek  can we look into this issue reported by Chris/Jeff ?

**Comment by sfc-gh-turbaszek** [comment] 2023-07-12 08:41
Is this a duplicate of https://github.com/Snowflake-Labs/snowcli/issues/219 ?

**Comment by sfc-gh-turbaszek** [comment] 2023-08-01 09:37
Closed via #246

**Closed by sfc-gh-turbaszek** 2023-08-01 09:37 UTC
